# codecov.yml
coverage:
  status:
    project:
      default:
        target: 60
        threshold: 2
    patch:
      default:
        target: 75
        threshold: 2
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
ignore:
  - "test/*"
  - "src/**/*.spec.ts"
